"""initial schema

Revision ID: 2e092cffdd45
Revises:
Create Date: 2026-05-30 23:36:52.547505
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = "2e092cffdd45"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approvals",
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_approvals_target_id"), "approvals", ["target_id"], unique=False)
    op.create_index(op.f("ix_approvals_target_type"), "approvals", ["target_type"], unique=False)
    op.create_table(
        "kb_chunks",
        sa.Column("chunk_key", sa.String(length=256), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("section", sa.String(length=128), nullable=True),
        sa.Column("source_priority", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=2048), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chunk_key"),
    )
    op.create_index(op.f("ix_kb_chunks_source"), "kb_chunks", ["source"], unique=False)
    op.create_table(
        "personas",
        sa.Column("persona_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("trigger_keywords", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("recommended_messaging", sa.Text(), nullable=False),
        sa.Column("marketing_opportunity", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("persona_id"),
    )
    op.create_table(
        "tickets",
        sa.Column("ticket_id", sa.String(length=64), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("message_body", sa.Text(), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=True),
        sa.Column("customer_name", sa.String(length=128), nullable=True),
        sa.Column("customer_email", sa.String(length=256), nullable=True),
        sa.Column("date_received", sa.String(length=32), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tickets_ticket_id"), "tickets", ["ticket_id"], unique=True)
    op.create_table(
        "runs",
        sa.Column("ticket_id", sa.Uuid(), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("question_type", sa.String(length=64), nullable=True),
        sa.Column("buyer_persona", sa.String(length=64), nullable=True),
        sa.Column("escalation_flags", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("classification_confidence", sa.Float(), nullable=True),
        sa.Column("kb_confidence", sa.Float(), nullable=True),
        sa.Column("kb_top_source", sa.String(length=128), nullable=True),
        sa.Column("route", sa.String(length=32), nullable=True),
        sa.Column("route_reason", sa.Text(), nullable=True),
        sa.Column("notes", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_runs_ticket_id"), "runs", ["ticket_id"], unique=False)
    op.create_table(
        "gaps",
        sa.Column("ticket_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("paraphrase", sa.Text(), nullable=False),
        sa.Column("theme", sa.String(length=64), nullable=True),
        sa.Column("buyer_persona", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("resolved_by", sa.String(length=128), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("kb_entry_draft", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gaps_status"), "gaps", ["status"], unique=False)
    op.create_index(op.f("ix_gaps_ticket_id"), "gaps", ["ticket_id"], unique=False)
    op.create_table(
        "replies",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("citations", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_replies_run_id"), "replies", ["run_id"], unique=False)
    op.create_index(op.f("ix_replies_status"), "replies", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_replies_status"), table_name="replies")
    op.drop_index(op.f("ix_replies_run_id"), table_name="replies")
    op.drop_table("replies")
    op.drop_index(op.f("ix_gaps_ticket_id"), table_name="gaps")
    op.drop_index(op.f("ix_gaps_status"), table_name="gaps")
    op.drop_table("gaps")
    op.drop_index(op.f("ix_runs_ticket_id"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_tickets_ticket_id"), table_name="tickets")
    op.drop_table("tickets")
    op.drop_table("personas")
    op.drop_index(op.f("ix_kb_chunks_source"), table_name="kb_chunks")
    op.drop_table("kb_chunks")
    op.drop_index(op.f("ix_approvals_target_type"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_target_id"), table_name="approvals")
    op.drop_table("approvals")
    # ### end Alembic commands ###
